### ISSUE TITLE
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.

### ISSUE THREAD

**Issue by obykoo** [javascriptiscoolpl/npm-simple-react-pdf#1]
When runing minifed version in production , then i am getting this error...

**Comment by javascriptiscoolpl** [comment]
As I remember this is related to wrong pdf file (maybe too advanced structure with special characters or fonts). Please share link to the pdf file, I will try to check what is going on there.
