### ISSUE TITLE
create some hooks

### ISSUE THREAD

**Issue by alondahari** [javascriptiscoolpl/npm-simple-react-pdf#4]
Hi,
I think your package would be more useful if you added some event hooks to it.
onDocumentLoad, onDocumentError etc.

Thanks!

**Comment by javascriptiscoolpl** [comment]
Do you know how to do that? because I am not able to catch any error with the mozilla library https://github.com/javascriptiscoolpl/npm-simple-react-pdf/pull/3. The `try` and `catch` also not works. The mozilla library is **very very wrongly written**.
