### ISSUE TITLE
multiple canvas elements being rendered

### ISSUE THREAD

**Issue by YOO629** [javascriptiscoolpl/npm-simple-react-pdf#5]
Hi, thanks for the great package.

I'm using this module to render a pdf that I'm retrieving from S3. The code looks like this:

```
<spdf.SimplePDF file={this.props.signedUrl}/>
```

However, I'm noticing that multiple canvas elements are appended to the dom, which means that I have multiple views of the same element. I wanted to drop a line here and see if you have any advice.

It seems like the number of canvas elements that are rendered is tied to how many times `React.render()` is called, though I don't have any solid proof of this.

Any help would be appreciated. Thanks.

**Comment by javascriptiscoolpl** [comment]
Thanks for your comment. I am not sure if I correct understand the question but the canvas is created per each pdf page. So if you have single page pdf you should get 1 canvas in DOM but if you have many (e.g. 5) pages in your pdf document you should get many (e.g. 5) canvas in this case. If you would change the logic of it (e.g. 1 canvas for all document) you had to make your own scrolling method in canvas (it is very problematic way to do this and keep it responsible later on all devices). Nice profile picture by the way :-)

**Comment by YOO629** [comment]
The issue is that it's a 1 page PDF document, but I have multiple canvas elements being rendered, so I have the same PDF being rendered multiple times.

**Comment by javascriptiscoolpl** [comment]
I guess this shouldn't be like that. There should be 1 canvas for each React Simple pdf component. However make a note, that if you have e.g. 3 components like this:
```
<spdf.SimplePDF file={this.props.signedUrl}/>
<spdf.SimplePDF file={this.props.signedUrl}/>
<spdf.SimplePDF file={this.props.signedUrl}/>
```
there will be 3 canvas in this case (1 for each react component).
Can you share the pdf document somehow? so I will try to test it then.

**Comment by YOO629** [comment]
I unfortunately can't share the PDF because of company reasons, but this is no longer an issue for me -- I was generating the pdf from html, so instead of serving the s3 signed url to the client and forcing the download, I sent over the html used to generate the pdf and render that instead now.

**Comment by javascriptiscoolpl** [comment]
Too bad you can't share it. However, I am happy you have it working now.
