### ISSUE TITLE
Error "InvalidPDFException"

### ISSUE THREAD

**Issue by milencheto** [javascriptiscoolpl/npm-simple-react-pdf#6]
Hello, I have this error. Can you help me with?

![image](https://user-images.githubusercontent.com/10586251/29074223-26437320-7c57-11e7-9c61-05c2adf5721f.png)

**Comment by javascriptiscoolpl** [comment]
Hi, as far as I remember this kind of errors are usually related to wrong or more advanced pdf documents. This may happen if you use some extra fonts, symbols or specific language fonts. However to be sure and to help you somehow, I would like to have some pdf sample that causes this error. If your pdf is private try to prepare other document with such error and please share it somehow to me. I will try to debug this plugin code, find out what is going on and release some fixes in code if needed. You can also try on your own any localization library, usually l10n helps.

**Comment by milencheto** [comment]
Hey, thanks for the fast reply... my .pdf is kinda private, yes, but I also tried with the example1.pdf from demo folder... and the result is the same :(

**Comment by javascriptiscoolpl** [comment]
Well... this is strange if so. The examples included in demo should load fine. I will check env soon, rebuild everything and look into it. Maybe there are some dependencies problem, new version of the lib that is no backward compatible or something like that. Stay tunned, let you know soon.

**Comment by milencheto** [comment]
thank you in advance

**Comment by javascriptiscoolpl** [comment]
Hi again, I have tested this issue in the clean node (empty directory). I was able to open index.html without any problems: 
```
npm install simple-react-pdf
cd ./node_modules/simple-react-pdf/demo
firefox index.html
```
and also rebuild demo and open index.html again like this:
```
cd ./node_modules/simple-react-pdf/demo
npm run build
firefox index.html
```
also I was able to rebuild simple-react-pdf module again for demo and demo itself like this:
```
cd ./node_modules/simple-react-pdf/demo/node_modules/simple-react-pdf
npm run build
cd ..
cd ..
npm run transform
firefox index.html
```

So this looks like there is some work in dependent libraries if the build error occur sometimes. So what You can do is:
- try to use built version of simple-react-pdf module (without rebuilding it)
- try to wait until they fix errors in dependent libraries
- try to use more stable (earlier) version of dependent libraries

However looks like the build works fine now. So everything should be fine without any changes.
Also there might be Your environment issue. Try to correct some paths or env variables.

**Comment by javascriptiscoolpl** [comment]
Feel free to reopen or open new issue related to the module code. Thanks.
