### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getElementsByClassName' of null  (React 16)

### ISSUE THREAD

**Issue by Mikeysax** [javascriptiscoolpl/npm-simple-react-pdf#8]
Getting this when using React 16:
```
index.js:48 Uncaught TypeError: Cannot read property 'getElementsByClassName' of null
    at SimplePDF.loadPDF (index.js:48)
    at SimplePDF.componentDidMount (index.js:107)
    at commitLifeCycles (react-dom.development.js:11505)
    at commitAllLifeCycles (react-dom.development.js:12294)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
    at invokeGuardedCallback (react-dom.development.js:1195)
    at commitAllWork (react-dom.development.js:12415)
    at workLoop (react-dom.development.js:12687)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
loadPDF @ index.js:48
componentDidMount @ index.js:107
commitLifeCycles @ react-dom.development.js:11505
commitAllLifeCycles @ react-dom.development.js:12294
callCallback @ react-dom.development.js:1299
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195
commitAllWork @ react-dom.development.js:12415
workLoop @ react-dom.development.js:12687
callCallback @ react-dom.development.js:1299
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195
performWork @ react-dom.development.js:12800
batchedUpdates @ react-dom.development.js:13244
performFiberBatchedUpdates @ react-dom.development.js:1646
stackBatchedUpdates @ react-dom.development.js:1637
batchedUpdates @ react-dom.development.js:1651
batchedUpdatesWithControlledComponents @ react-dom.development.js:1664
dispatchEvent @ react-dom.development.js:1874
react-dom.development.js:8305 The above error occurred in the <SimplePDF> component:
    in SimplePDF (created by DocumentCard)
    in div (created by DocumentCard)
    in DocumentCard (created by Lesson)
    in div (created by Lesson)
    in div (created by Lesson)
    in div (created by Lesson)
    in div (created by Lesson)
    in div (created by Lesson)
    in Lesson (created by Connect(Lesson))
    in Connect(Lesson) (created by Connect(Connect(Lesson)))
    in Connect(Connect(Lesson)) (created by RouterContext)
    in div (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext
    in AsyncConnect (created by Connect(AsyncConnect))
    in Connect(AsyncConnect) (created by Router)
    in Router
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
You can learn more about error boundaries at https://fb.me/react-error-boundaries.
logCapturedError$1 @ react-dom.development.js:8305
captureError @ react-dom.development.js:12993
commitAllWork @ react-dom.development.js:12423
workLoop @ react-dom.development.js:12687
callCallback @ react-dom.development.js:1299
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195
performWork @ react-dom.development.js:12800
batchedUpdates @ react-dom.development.js:13244
performFiberBatchedUpdates @ react-dom.development.js:1646
stackBatchedUpdates @ react-dom.development.js:1637
batchedUpdates @ react-dom.development.js:1651
batchedUpdatesWithControlledComponents @ react-dom.development.js:1664
dispatchEvent @ react-dom.development.js:1874
index.js:48 Uncaught TypeError: Cannot read property 'getElementsByClassName' of null
    at SimplePDF.loadPDF (index.js:48)
    at SimplePDF.componentDidMount (index.js:107)
    at commitLifeCycles (react-dom.development.js:11505)
    at commitAllLifeCycles (react-dom.development.js:12294)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
    at invokeGuardedCallback (react-dom.development.js:1195)
    at commitAllWork (react-dom.development.js:12415)
    at workLoop (react-dom.development.js:12687)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
```

**Comment by slipperypenguin** [comment]
Having this exact same issue. Going to try updating `react` and `react-dom` to v16.0.0 in `node_modules/simple-react-pdf/package.json` and see if that fixes anything.

![screen shot 2017-09-27 at 10 37 39 am](https://user-images.githubusercontent.com/3655354/30919618-f003bac8-a36f-11e7-9ff0-3486e98251f6.png)

**Comment by javascriptiscoolpl** [comment]
Hi @Mikeysax and @slipperypenguin, Thanks for the issue. I will try to check if the issue is code related or environment one. Probably let You know Tomorrow, I will try to test it Today late evening or night.

**Comment by javascriptiscoolpl** [comment]
I tested out everything and there is no problem during rebuild or working process. Everything works fine to me as it was before under Firefox. 

However, there is new small warning during the build about deprecated `babel-preset-es2015` and they recommend to use new invention `babel-preset-env` but this not impact the build or working process at any level. For sure I will take care of it in the future but now I don't see any reason for code changes. 

Please verify Your environment or Your private code changes (if there are such any). Also please feel free to reopen this issue if there is specific browser error and occurs only in other kind of browser.

**Comment by Mikeysax** [comment]
The previous error I posted was from Chrome. This is from Firefox:
```
TypeError: _reactDom2.default.findDOMNode(...) is null[Learn More]  bundle.js:207828:18
"The above error occurred in the <SimplePDF> component:
    in SimplePDF (created by Document)
    in div (created by Document)
    in Document (created by Connect(Document))
    in Connect(Document) (created by RouterContext)
    in div (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext
    in AsyncConnect (created by Connect(AsyncConnect))
    in Connect(AsyncConnect) (created by Router)
    in Router
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
You can learn more about error boundaries at https://fb.me/react-error-boundaries."  bundle.js:149021:5
GET DOCUMENT ERROR:  TypeError: _reactDom2.default.findDOMNode(...) is null
Stack trace:
loadPDF@http://localhost:8080/dist/bundle.js:207828:18
componentDidMount@http://localhost:8080/dist/bundle.js:207887:7
commitLifeCycles@http://localhost:8080/dist/bundle.js:152221:15
commitAllLifeCycles@http://localhost:8080/dist/bundle.js:153010:9
callCallback@http://localhost:8080/dist/bundle.js:142015:9
invokeGuardedCallbackDev@http://localhost:8080/dist/bundle.js:142054:7
invokeGuardedCallback@http://localhost:8080/dist/bundle.js:141911:5
commitAllWork@http://localhost:8080/dist/bundle.js:153131:9
workLoop@http://localhost:8080/dist/bundle.js:153403:13
callCallback@http://localhost:8080/dist/bundle.js:142015:9
invokeGuardedCallbackDev@http://localhost:8080/dist/bundle.js:142054:7
invokeGuardedCallback@http://localhost:8080/dist/bundle.js:141911:5
performWork@http://localhost:8080/dist/bundle.js:153516:7
scheduleUpdateImpl@http://localhost:8080/dist/bundle.js:153901:19
scheduleUpdate@http://localhost:8080/dist/bundle.js:153840:12
enqueueSetState@http://localhost:8080/dist/bundle.js:150362:7
./node_modules/react/cjs/react.development.js/ReactComponent.prototype.setState@http://localhost:8080/dist/bundle.js:186824:3
onStateChange@http://localhost:8080/dist/bundle.js:162558:11
notify@http://localhost:8080/dist/bundle.js:162286:9
notifyNestedSubs@http://localhost:8080/dist/bundle.js:162325:5
onStateChange@http://localhost:8080/dist/bundle.js:162555:11
dispatch@http://localhost:8080/dist/bundle.js:207082:7
routerMiddleware/</</<@http://localhost:8080/dist/bundle.js:163304:18
createThunkMiddleware/</</<@http://localhost:8080/dist/bundle.js:206883:16
promiseMiddleware/</<@http://localhost:8080/dist/bundle.js:206857:12
dispatch@http://localhost:8080/dist/bundle.js:207427:18
./shared/js/actions/document.js/exports.getDocument/</<@http://localhost:8080/dist/bundle.js:239701:5
```
When I comment it out, it doesn't error. Not sure why it's not working anymore.

Currently, I'm using React / React-DOM 16.0.0 in an Isomorphic React Application / Webpack. It was working until I updated to React / ReactDOM 16.

**Comment by slipperypenguin** [comment]
I believe the issue is that simple-react-pdf is using React v15.0.0, while our apps are running React v16.0.0, which includes a few breaking changes and depreciations. Facebook has a blog post detailing them [here](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html).

**Comment by Mikeysax** [comment]
Yes, @javascriptiscoolpl Did you update to React / ReactDOM 16.0.0 and test the current version of simple-react-pdf ?

**Comment by slipperypenguin** [comment]
@javascriptiscoolpl @Mikeysax So it looks like when there is an explicit dependency of react in a package (such as `simple-react-pdf` using 15.0.0), it pulls a second copy of react in and uses that, which can cause errors - see this issue on the [react repo](https://github.com/facebook/react/issues/10320). Specifically [this comment](https://github.com/facebook/react/issues/10320#issuecomment-332353869)

**Comment by javascriptiscoolpl** [comment]
I tested with the newest version marked in `package.json` file as `^`. It has not been tested with `16.0.0` yet but will be for sure. 

However, the `react` https://www.npmjs.com/package/react and `react-dom` https://www.npmjs.com/package/react-dom package has been released 3 days ago. It is really hard to believe that anyone can take the `16.0.0` version seriously in real life application. There is no software upgrade politics, feature, schedule? just clicking button? seriously?

Also I don't see that `getElementsByClassName` is deprecated in any official JavaScript documentation, so I am guessing this should not be a problem, if there is no serious bug in the newest `16.0.0` experimental library. 

I will test it also with the new experimental library soon and let You know. I hope I will be able to reproduce this error, because I was not able to reproduce it so far, so this is why I closed this ticked with no change.

**Comment by javascriptiscoolpl** [comment]
@Mikeysax and @slipperypenguin, I have just made small tests with the new "experimental" libraries and I did not find any problems with that. So looks like the problem must be somewhere else. 

I will switch to the new version of react and react-dom and probably together with babel-env but this need more time (about half a year or first stable patches at least). This new version looks too new to me and I am not sure what expect from them. In my opinion is too risky to build something on that for real. But of course is up to You what You do and You are welcome to make fork.

Thanks for this issue, I will keep track on that.

**Comment by Mikeysax** [comment]
@javascriptiscoolpl All you have to do is move React and ReactDOM into `peerDependencies` as version 16. You could even use both with an OR operator and nothing would break. I'm also already using babel-env, nothing has broken.

I did this in my projects node modules folder and it fixed the problem.

**Comment by javascriptiscoolpl** [comment]
Nice to hear it is working for You now. Thanks @Mikeysax, I will consider this issue for sure in the future.
